Repository nerd-team-1/favorite-18-server, pull requests merged in 2024-06, with the labels that each got.

#5 [DOCS] README 추가
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/issue--enhancement.md
  .github/ISSUE_TEMPLATE/issue--fix.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
Labels: documentation

#7 [BE] [FEATURE] 유저, 인증 기능 구현
  core/core-api/build.gradle
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/annotation/Business.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/annotation/Converter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/annotation/UserSession.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/client/OAuth2Client.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/RestTemplateConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/WebConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/intercepter/AuthorizationInterceptor.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/resolver/UserSessionResolver.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/business/AuthBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthOpenApiController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/dto/request/AuthGoogleAccessTokenRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/dto/request/AuthRefreshRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/dto/response/AuthGoogleAccessTokenResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/model/GoogleUserInfo.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/model/OAuth2UserInfo.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/business/JwtBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/converter/JwtConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/dto/JwtRefreshResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/dto/JwtResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/helper/TokenHelper.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/helper/TokenHelperImpl.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/model/Token.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/service/JwtService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/support/error/ErrorCode.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/support/error/ErrorType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/support/response/ApiResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/business/UserBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/converter/UserConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/UserDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/request/UserRegisterRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/request/UserUpdateNicknameRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/service/UserService.java
  core/core-api/src/main/resources/application.yml
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/entity/User.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/repository/UserRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserGender.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserRole.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserStatus.java
  storage/db-core/src/main/resources/db-core.yml
Labels: enhancement

#12 [FIX] Swagger UI 에러 해결 외 기타 수정
  core/core-api/build.gradle
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/AsyncConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/AsyncExceptionHandler.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/SwaggerConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/WebConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/ApiControllerAdvice.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/HealthController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/ExampleController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/request/ExampleRequestDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/response/ExampleResponseDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleData.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleResult.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/intercepter/AuthorizationInterceptor.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/resolver/UserSessionResolver.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/CoreApiException.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorCode.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorMessage.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/response/ApiResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/response/ResultType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthOpenApiController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/controller/v1/response/ExampleResponseDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/domain/ExampleResult.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/helper/TokenHelperImpl.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/service/JwtService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/support/response/ResultType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/service/UserService.java
  core/core-api/src/main/resources/application.yml
  core/core-api/src/main/resources/static/favicon.ico
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserGender.java
Labels: bug

#14 [FEATURES] ENUM Type, Status 정의
  .gitignore
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/EnumCodeConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/WebConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/code/EnumController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/converter/UserConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/UserDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/service/UserService.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/common/EnumMapper.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/common/EnumMapperType.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/common/EnumMapperValue.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/qna/AnswerStatus.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/qna/QnaProgressStatus.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/song/MachineType.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/user/UserGender.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/user/UserRole.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/user/UserStatus.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/entity/User.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/repository/UserRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserGender.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserRole.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/type/UserStatus.java
  storage/db-core/src/test/java/com/nerd/favorite18/storage/db/CoreDbContextTest.java
  storage/db-core/src/test/java/com/nerd/favorite18/storage/db/CoreDbTestApplication.java
  storage/db-core/src/test/java/com/nerd/favorite18/storage/db/core/ExampleRepositoryIT.java
Labels: enhancement

#17 [FEATURE] Q&A 도메인 및 사용자 기능 구현
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorCode.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/business/QnaBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/controller/QnaController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/converter/QnaConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/QnaAddRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/QnaDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/service/QnaService.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/BaseEntity.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/BaseProjection.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/entity/Qna.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/projection/QnaListResponse.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/repository/QnaRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/repository/UserRepository.java
Labels: enhancement

#20 [FEATURE] 회원탈퇴 기능 구현
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/resolver/UserSessionResolver.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/business/AuthBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/business/UserBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/converter/UserConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/service/UserService.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/entity/User.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/repository/UserRepository.java
Labels: enhancement

#24 [FEATURE] 즐겨찾기 기능 구현
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/business/SongLikeBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongLikeController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/converter/SongLikeConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/SongDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/SongLikeDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/service/SongLikeService.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/entity/SongLike.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/projection/SongLikeProjection.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/projection/SongProjection.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/repository/SongLikeRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/repository/SongRepository.java
Labels: enhancement

#26 [FEATURE] 노래관리 기능 구현 완료
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/SpringDataWebConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorCode.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/utils/FavoriteStringUtils.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/business/SongBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/converter/SongConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/converter/SongQueryConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/request/SongCodeRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/request/SongCreateRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/request/SongUpdateRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/response/SongCodeResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/dto/response/SongResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/service/SongManageService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/service/SongSelectService.java
  core/core-api/src/main/resources/application.yml
  sqlfiles/SongDDL.zip
  storage/db-core/build.gradle
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/config/QueryDSLConfig.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/dto/SongCodeQueryDto.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/dto/SongQueryDto.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/entity/Song.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/entity/SongCode.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/repository/SongCustomRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/repository/SongCustomRepositoryImpl.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/repository/SongRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/entity/User.java
  storage/db-core/src/main/resources/db-core.yml
Labels: enhancement

#29 [FEATURE] 관리자의 사용자 기능 구현
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/WebConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/intercepter/AuthenticationInterceptor.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/intercepter/AuthorizationInterceptor.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/resolver/UserSessionResolver.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/business/JwtBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/jwt/service/JwtService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/business/UserAdminBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/business/UserBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/UserDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/request/UserUpdateUserRoleRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/service/UserService.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/entity/User.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/projection/UserListResponse.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/repository/UserRepository.java
Labels: enhancement

#33 [CHORE] CI와 CD를 구축합니다.
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  core/core-api/build.gradle
Labels: CI/CD

#36 [FIX] CD시 SCP가 Server와 연결이 안되는 Issue 수정
  .github/workflows/cd.yml
Labels: CI/CD

#27 [FEATURE] 인기곡 랭킹 기능 구현 중간점검
  core/core-api/build.gradle
  core/core-api/src/main/java/com/nerd/favorite18/CoreApiApplication.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/RedisConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/business/RankBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRadisController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/converter/RankConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/dto/RankDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/dto/request/RankAddRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RankService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/service/RedisRankService.java
  core/core-api/src/main/resources/application.yml
  core/core-api/src/test/java/com/nerd/favorite18/CoreApiDbTestApplication.java
  core/core-api/src/test/java/com/nerd/favorite18/service/RankServiceTest.java
  core/core-batch/build.gradle
  core/core-batch/src/main/java/com/nerd/favorite18/BatchApplication.java
  core/core-batch/src/main/java/com/nerd/favorite18/job/rank/RankTasklet.java
  storage/db-core/build.gradle
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/entity/Rank.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/projection/RankListResponse.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/ranking/repository/RankRepository.java
  storage/db-core/src/main/resources/db-core.yml
Labels: enhancement

#31 [FEATURE] 관리자의 Q&A 관리 기능 구현
  core/core-api/src/main/java/com/nerd/favorite18/CoreApiApplication.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/component/LocalBaseDataLoader.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/AppPropertiesConfig.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/business/QnaAdminBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/business/QnaBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/controller/QnaAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/controller/QnaController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/converter/QnaConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/converter/QnaQueryConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/QnaDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/request/QnaAddRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/request/QnaUpdateRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/dto/response/QnaResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/service/QnaService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/converter/UserQueryConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/dto/response/UserResponse.java
  core/core-api/src/main/resources/application.yml
  core/core-api/src/test/java/com/nerd/favorite18/CoreApiApplicationTests.java
  core/core-api/src/test/java/com/nerd/favorite18/core/api/qna/business/QnaAdminBusinessTest.java
  core/core-api/src/test/resources/application.yml
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/qna/QnaProgressStatus.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/dto/QnaQueryDto.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/entity/Qna.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/repository/QnaCustomRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/repository/QnaCustomRepositoryImpl.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/qna/repository/QnaRepository.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/user/dto/UserQueryDto.java
Labels: enhancement

#39 [FIX] 프로젝트의 자잘한 수정 사항 해결
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/ExampleController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/request/ExampleRequestDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/controller/v1/response/ExampleResponseDto.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleData.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleResult.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/domain/ExampleService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/ApiControllerAdvice.java
  core/core-enum/src/main/java/com/nerd/favorite18/core/enums/user/UserGender.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/song/entity/SongLike.java
Labels: wontfix

#41 [FIX] CORS 이슈 수정
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/WebConfig.java
Labels: wontfix

#43 fix : Swagger에서 CORS가 발생되는 이슈 수정
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/config/SwaggerConfig.java
Labels: wontfix
