Repository nerd-team-1/favorite-18-server, pull requests merged in 2024-08, with the labels that each got.

#54 [FEATURE] 점수 분석 모델 개발
  .gitignore
  core/core-api/build.gradle
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorCode.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/support/error/ErrorType.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/utils/ConvertUtils.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/_common/utils/StringUtils.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/business/ModelScoreBusiness.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/controller/ModelScoreController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/converter/ModelConverter.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/dto/request/ModelScoreRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/dto/request/ModelUploadRequest.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/dto/response/ModelScoreListResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/dto/response/ModelScoreResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/dto/response/ModelUploadResponse.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/model/ScoreResult.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/service/ModelScoreService.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/service/SongLikeService.java
  core/core-api/src/main/resources/application.yml
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/model/entity/ModelScore.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/model/projection/ModelScoreProjection.java
  storage/db-core/src/main/java/com/nerd/favorite18/storage/db/core/model/repository/ModelScoreRepository.java
Labels: enhancement

#57 fix : 오류 추적을 위한 Log추가입니다. #56
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/business/ModelScoreBusiness.java
Labels: bug

#59 [ERROR / BUG] 점수 모델 운영 서버 실행 에러
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/business/ModelScoreBusiness.java
Labels: bug, wontfix

#61 [ERROR / BUG] 점수 모델 운영 서버 실행 명령어 에러
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/business/ModelScoreBusiness.java
Labels: bug, wontfix

#64 [DOCUMENT] Swagger의 Controller, Method에 기록될 API설명 추가.
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/auth/controller/AuthOpenApiController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/code/EnumController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/model/controller/ModelScoreController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/controller/QnaAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/qna/controller/QnaController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/ranking/controller/RankRedisController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/song/controller/SongLikeController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserAdminController.java
  core/core-api/src/main/java/com/nerd/favorite18/core/api/user/controller/UserController.java
Labels: documentation
